---
- name: apt-get | apt-get update
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  become: true

- name: apt-get | ensure core packages are installed
  apt: 
    pkg: [
      'atool',
      'atop',
      'curl',
      'git',
      'make',
      'mc',
      'supervisor',
      'tig',
      'tree',
      'vim',
      'unzip',
      'memcached',
      'redis',
      'libpng-dev',
    ]
    state: present
  become: true